# Generated by Django 3.1.7 on 2021-04-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='links_values',
        ),
        migrations.RemoveField(
            model_name='message',
            name='texts_out_links',
        ),
    ]
