# Generated by Django 3.1.7 on 2021-04-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_auto_20210418_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='links_FIT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_Ol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
