# Generated by Django 3.1.7 on 2021-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, default='"Без названия"', max_length=20, null=True),
        ),
    ]
