# Generated by Django 3.1.7 on 2021-04-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_auto_20210418_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text_Ol',
            new_name='texts_Ol',
        ),
    ]
