# Generated by Django 3.1.7 on 2021-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_auto_20210418_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='texts_Ol',
        ),
        migrations.AddField(
            model_name='message',
            name='texts_FIT',
            field=models.TextField(blank=True, null=True),
        ),
    ]
