# Generated by Django 3.1.7 on 2021-06-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_note_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='MessagesFiles'),
        ),
    ]
