# Generated by Django 3.1.7 on 2021-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0005_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='MessagesFiles'),
        ),
    ]
