# Generated by Django 3.1.7 on 2021-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0006_auto_20210624_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='MessagesFiles'),
        ),
    ]
