# Generated by Django 3.1.7 on 2021-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0006_auto_20210422_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, default='notes/web_chat_imgs/фон_д_к.png', null=True, upload_to='images/sections'),
        ),
    ]
