# Generated by Django 3.1.7 on 2021-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0007_auto_20210422_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sections'),
        ),
    ]
