# Generated by Django 3.1.7 on 2021-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0007_auto_20210624_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
