# Generated by Django 3.1.7 on 2021-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0008_auto_20210423_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='text',
            field=models.TextField(max_length=65),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=550),
        ),
    ]
