# Generated by Django 3.1.7 on 2021-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0009_auto_20210427_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='text',
            field=models.TextField(max_length=265),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=950),
        ),
    ]
