# Generated by Django 3.1.7 on 2021-07-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0009_auto_20210624_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_file_type',
            field=models.CharField(default='file', max_length=25),
            preserve_default=False,
        ),
    ]
