# Generated by Django 3.1.7 on 2021-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0010_message_attached_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attached_file_type',
            field=models.TextField(),
        ),
    ]
