# Generated by Django 3.1.7 on 2021-07-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0011_auto_20210726_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attached_file_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
